intf_libs = # Interface dependencies.
import intf_libs += lyrahgames-xstd%lib{lyrahgames-xstd}
import intf_libs += fmt%lib{fmt}

lib{lyrahgames-log}: {hxx ixx txx}{** -version} hxx{version} $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{lyrahgames-log}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# Install into the lyrahgames-log/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/lyrahgames/log/
  install.subdirs = true
}
